apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: stackeye-stg

resources:
  - image-catalog.yaml
  - cluster.yaml
  - service-lb.yaml
  - service-tailscale.yaml
  - scheduled-backup.yaml
